////////////////////////////////
//:.  Lae'lyil Greets Lena  .://
////////////////////////////////

IF  
    InParty("EU#LENA")
    !StateCheck("EU#LENA",CD_STATE_NOTVALID)
    !StateCheck(Player1,CD_STATE_NOTVALID)
    OR(2)
        See(Player1)
        See("EU#LENA")
    Global("EU#LenaLealiylMeeting","LOCALS",0)
THEN
    RESPONSE #1
        SetGlobal("EU#LenaLealiylMeeting","LOCALS",1)
        StartDialogueNoSet(Player1)
END